services:
  mongodb:
    image: mongo:latest
    container_name: my_social_network_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: my_social_network_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: false
      # ME_CONFIG_MONGODB_ADMINUSERNAME: HHED
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password_HHED
      # ME_CONFIG_MONGODB_SERVER: mongodb
      # ME_CONFIG_BASICAUTH_USERNAME: HHED
      # ME_CONFIG_BASICAUTH_PASSWORD: adminHHED

volumes:
  mongodb_data: